### ISSUE TITLE
Match image with grabResult in async capture mode (with callback)

### ISSUE THREAD

**Issue by keven425** [basler/pypylon#135]
I'm using this example to grab:
https://github.com/basler/pypylon/blob/master/samples/grabusinggrabloopthread.py

It uses a separate thread running pylon.ImageEventHandler. OnImageGrabbed
gets called when an image result is available.

I want to associate the capture() function call with the grabbed image. i.e.

I call

```
camera.capture_asnyc()
camera.capture_asnyc()
```

... some time later `OnImageGrabbed()` gets called twice. I want to know, for
each grab result, which `capture_async()` call it corresponds to.

Is there a way to associate the grab result with capture?

**Comment by thiesmoeller** [comment]
The image will arrive at the callback-handler in strict order of acquisition. The transport layers do take care of this.
If you provide enough buffers to the background thread you'll get every frame.

One idea for your request:

Give your `capture_async()`  method a new argument like `reference`: 
```
camera.capture_asnyc(0x10)
camera.capture_asnyc(0x20)
```

And in capture_async you push your reference to a [queue](https://docs.python.org/3/library/queue.html).

In the `OnImageGrabbed()` you can fetch the element back. And due to strong FIFO order, your have association.

[ have to take care to lock capture_async against concurrent access  of course ]
