### ISSUE TITLE
Import error _pylon 

### ISSUE THREAD

**Issue by Thkthomas** [basler/pypylon#414]
Hi 

Im currently working on a project involving two Basler Ace acA5472-17uc cameras. Which i would like to control from the following PyCharm code. Currently im only getting familiar with python so i dont know if i have made an obvious error. 
![Pyloncode](https://user-images.githubusercontent.com/91662281/135422960-39601129-a0f5-479d-ba4e-af9cea846d8f.png)
However when i try to import pylon from pypylon, i get an import error saying
![error](https://user-images.githubusercontent.com/91662281/135423976-d705704e-c30f-4e19-9239-e19ce5c28a65.png)
Can anybody help me with this?

Kind regards 
Thomas

**Comment by thiesmoeller** [comment]
Remove the pypylon folder from your directory. Python   will first search for import locally ... and fails ...

Because python requires modules(with binary extensions) to be properly installed into specific locations

This is all handled by `pip install ` as described in the readme.md of this project.

In pycharm you have some nice GUI support for it 

https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html
