### ISSUE TITLE
GetArray() vs Array?

### ISSUE THREAD

**Issue by hlacikd** [basler/pypylon#634]
Guys both GetArray() and Array return numpy array of frame, so what is a difference between them, other than GetArray() is more "pythonic"

```
with camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException) as grab:
  frame = grab.Array
```

vs

```
with camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException) as grab:
 frame = grab.GetArray()
```

in examples i've seen booth of them "Randomly" used.

Thanks in a advance for clarification

**Comment by HighImp** [comment]
Hello, 
both ways are the same, "Array" is just the getter property for "GetArray".
(see; https://github.com/search?q=repo%3Abasler%2Fpypylon%20ADD_PROP_GET&type=code)

Its the same with "GetValue"/"SetValue"  and just "Value".
https://github.com/search?q=repo%3Abasler%2Fpypylon%20path%3A%2F%5Esrc%5C%2Fgenicam%5C%2F%2F%20PROP_GETSET&type=code

It depends on what you like the most. 
Personally, I like the property methods much better because:

```{python}
cam.ExposureTime.Value = cam.ExposureTime.Min 
```

is IMHO simpler and more pythonic than

```{python}
cam.ExposureTime.SetValue(cam.ExposureTime.GetMin())
```
