### ISSUE TITLE
a2a4504-5gcPRO not reachable, other cameras fine

### ISSUE THREAD

**Issue by andrewseddon** [basler/pypylon#690]
We have multiple cameras running fine in IP address range 10.20.5.* . We have added two new a2a4504-5gcPRO cameras, and they drop in and out of the IP configurator randomly (PylonViewer fails to download XML file). As you can see in this screenshot one of the new cameras has the IP 10.20.5.20 and the PC has the IP 10.20.5.5 . Despite being in the subnet, we get a warning "The device is unreachable!".

![Screenshot 2023-11-22 at 16 51 02](https://github.com/basler/pypylon/assets/446928/9a072265-5c82-4e2c-b751-ea91f7aabcb4)

The problem seems to be isolated to the new a2a4504-5gcPRO cameras. We have tried all combinations of cables, ports etc. Any ideas?

**Comment by m-binev** [comment]
@andrewseddon Hi, well, I don't see the issue with my camera (which is different than yours), which is why I would suggest that you get in touch with your (local) Basler support team and check for any camera firmware updates for your camera model. When doing so, please make sure to provide the camera model name, serial number, current firmware version (typically in pylon Viewer > your camera > Device Control) and issue description. Cheers
